[workspace]
members = [
    "crates/engine_core",
    "crates/ws_binance",
    "crates/ws_hyperliquid",
    "crates/exec_hyperliquid",
    "crates/spsc",
    "crates/metrics",
    "crates/bins",
    "crates/replay_binance",
    "xtask",
]

resolver = "2"
