[package]
name = "replay_binance"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
lexical-core = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[dev-dependencies]
serde_json = "1"
